In [1]:

import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity



In [ ]:
movies_data = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies_data.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [4]:
movies_data.shape

(4803, 20)

In [5]:
selected_features = ['title','tagline','status','overview']
print(selected_features)


['title', 'tagline', 'status', 'overview']


In [6]:
# Fill missing values in selected features
for feature in selected_features:
    movies_data[feature] = movies_data[feature].fillna('')

# Concatenate selected columns and store the result in a new column 'combined_features'
movies_data['combined_features'] = (
    movies_data['title'] + ' ' +
    movies_data['tagline'] + ' ' +
    movies_data['status'] + ' ' +
    movies_data['overview'] 
)

In [7]:
for feature in selected_features:
    movies_data[feature] = movies_data[feature].fillna('')

combined_features = movies_data['title'] +' '+  movies_data['tagline'] +' '+ movies_data['status'] +''+ movies_data['overview']

In [8]:
print(combined_features)

0       Avatar Enter the World of Pandora. ReleasedIn ...
1       Pirates of the Caribbean: At World's End At th...
2       Spectre A Plan No One Escapes ReleasedA crypti...
3       The Dark Knight Rises The Legend Ends Released...
4       John Carter Lost in our world, found in anothe...
                              ...                        
4798    El Mariachi He didn't come looking for trouble...
4799    Newlyweds A newlywed couple's honeymoon is upe...
4800    Signed, Sealed, Delivered  Released"Signed, Se...
4801    Shanghai Calling A New Yorker in Shanghai Rele...
4802    My Date with Drew  ReleasedEver since the seco...
Length: 4803, dtype: object


In [9]:
vectorizer = TfidfVectorizer()

In [10]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [11]:
print(feature_vectors)

  (0, 3846)	0.21669373487694785
  (0, 860)	0.16804073192873617
  (0, 1024)	0.06904260071006786
  (0, 15821)	0.21054113347500822
  (0, 1055)	0.040368566025594084
  (0, 14325)	0.2038449688999221
  (0, 7948)	0.18342596774866243
  (0, 2261)	0.12638400033893724
  (0, 21784)	0.19049715393160238
  (0, 2071)	0.12386768245602676
  (0, 3052)	0.07825915888385254
  (0, 13138)	0.14218110777463594
  (0, 22456)	0.195881077035841
  (0, 14228)	0.06566954982978301
  (0, 13300)	0.20096216822162688
  (0, 21696)	0.039135046015114694
  (0, 5935)	0.23442737496691818
  (0, 10682)	0.05262861251781654
  (0, 12504)	0.20701650921610384
  (0, 14682)	0.27835759600223403
  (0, 3509)	0.16106720054115736
  (0, 240)	0.24932129930163613
  (0, 17189)	0.12109023079768569
  (0, 14642)	0.46885474993383636
  (0, 14142)	0.040299243698760534
  :	:
  (4802, 21496)	0.07312458019963484
  (4802, 14004)	0.07498849258586933
  (4802, 9060)	0.09621897478075321
  (4802, 23309)	0.095068208056939
  (4802, 14192)	0.07059506207173688
  (48

COSINE SIMILARITY

In [12]:
similarity = cosine_similarity(feature_vectors)

In [13]:
print(similarity)

[[1.         0.06236077 0.01818237 ... 0.03549125 0.01514278 0.01005778]
 [0.06236077 1.         0.04431337 ... 0.06557353 0.05289375 0.02290026]
 [0.01818237 0.04431337 1.         ... 0.03052096 0.0121865  0.01794479]
 ...
 [0.03549125 0.06557353 0.03052096 ... 1.         0.03472173 0.01864236]
 [0.01514278 0.05289375 0.0121865  ... 0.03472173 1.         0.03928165]
 [0.01005778 0.02290026 0.01794479 ... 0.01864236 0.03928165 1.        ]]


In [14]:
print(similarity.shape)


(4803, 4803)


In [29]:
movie_name = input(' Enter your favourite movie name : ')

In [30]:
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [31]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Spider-Man 3', 'Spider-Man 2', 'Spider-Man']


In [32]:
close_match = find_close_match[0]
print(close_match)

Spider-Man 3


In [54]:
index_of_movie = movies_data[movies_data['title'] == 'Spider-Man 3'].index[0]
print("Index of", 'Spider-Man 3', ":", index_of_movie)


Index of Spider-Man 3 : 5


In [56]:
# getting a list of similar movies

similarity_scores = list(enumerate(similarity[index_of_movie]))
print(similarity_scores)


[(0, 0.03552943529584864), (1, 0.018858366327173158), (2, 0.014583153359042682), (3, 0.02136489816195238), (4, 0.02304208358967373), (5, 1.0000000000000004), (6, 0.027309890110264946), (7, 0.035975515463539054), (8, 0.014436675093853681), (9, 0.023931893961281436), (10, 0.029588696311508077), (11, 0.02049734889161842), (12, 0.04716472169720485), (13, 0.0512225924461806), (14, 0.07363968752256314), (15, 0.05502474459285555), (16, 0.020314211553931247), (17, 0.025487943770301284), (18, 0.044010203111774546), (19, 0.03797728309770718), (20, 0.26827635242395337), (21, 0.02964171033832716), (22, 0.02809747440291816), (23, 0.019754165778353806), (24, 0.023049994575264184), (25, 0.03359836444090922), (26, 0.05284730677952767), (27, 0.07762488281057926), (28, 0.0066802545121862865), (29, 0.034285938657994494), (30, 0.3086594292779073), (31, 0.043096547504156174), (32, 0.02845617758567688), (33, 0.01288136872833534), (34, 0.006233446561482848), (35, 0.013493893334539778), (36, 0.044038084762773

In [58]:
# For computing similarity_scores

length_of_similarity_scores = len(similarity_scores)
print("Number of similar movies:", length_of_similarity_scores)


Number of similar movies: 4803


In [60]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
print(sorted_similar_movies)


[(5, 1.0000000000000004), (159, 0.3641841371652246), (30, 0.3086594292779073), (1534, 0.29299544933427435), (38, 0.271602907242651), (20, 0.26827635242395337), (1699, 0.17442639482085653), (1318, 0.1641813814457354), (3085, 0.1386956519042173), (3129, 0.12727091394090423), (4664, 0.11944399542450453), (431, 0.11404904324359252), (3383, 0.11264231641772343), (4276, 0.11093960138519811), (1179, 0.10152409239080587), (1888, 0.09891646110293828), (227, 0.09663418494893049), (3361, 0.09432043857260813), (4791, 0.09170395542640197), (4456, 0.09033418773321202), (572, 0.09024435802823294), (4501, 0.08926838699208808), (245, 0.08601487567443251), (4594, 0.08486792476566196), (3607, 0.08461716034399706), (2018, 0.0845159556089415), (1975, 0.08413368711661082), (3526, 0.08302393039559582), (813, 0.08256345265035622), (1115, 0.08240828309149606), (1428, 0.08200556286079323), (3199, 0.08133577692480085), (1244, 0.0805702849736611), (2386, 0.08012729340996501), (1155, 0.07882973150505328), (3920, 0

In [61]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Spider-Man 3
2 . Spider-Man
3 . Spider-Man 2
4 . Arachnophobia
5 . The Amazing Spider-Man 2
6 . The Amazing Spider-Man
7 . Along Came a Spider
8 . The Thing
9 . Spider
10 . Jungle Shuffle
11 . Bronson
12 . Charlotte's Web
13 . Losin' It
14 . Def-Con 4
15 . I Love You, Man
16 . Eddie the Eagle
17 . Knight and Day
18 . Alien Zone
19 . Tin Can Man
20 . Raising Victor Vargas
21 . Hook
22 . Broken Vessels
23 . Tomorrow Never Dies
24 . The Broadway Melody
25 . The Beastmaster
26 . There's Something About Mary
27 . Win a Date with Tad Hamilton!
28 . The Sting
29 . Superman


MOVIE RECOMMENDATION SYSTEM

In [67]:
movie_name = input('Enter your favourite movie name: ')
list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match].index[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key=lambda x: x[1], reverse=True)

print('Movies suggested for you:\n')

i = 1
for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = movies_data.loc[index, 'title']
    if i < 30:
        print(i, '.', title_from_index)
        i += 1









Movies suggested for you:

1 . Superman
2 . Superman II
3 . Superman IV: The Quest for Peace
4 . Superman III
5 . Superman Returns
6 . Horse Camp
7 . Batman v Superman: Dawn of Justice
8 . Brick Lane
9 . Spaceballs
10 . Spider-Man 2
11 . Man of Steel
12 . The Out-of-Towners
13 . Rise of the Guardians
14 . World War Z
15 . Bronson
16 . The Shipping News
17 . Wayne's World
18 . My Boss's Daughter
19 . Fly Me to the Moon
20 . You Can't Take It With You
21 . Iron Man 2
22 . How to Fall in Love
23 . American Hero
24 . Good Boy!
25 . The Amazing Spider-Man
26 . Spider-Man 3
27 . What Planet Are You From?
28 . Seeking a Friend for the End of the World
29 . Keeping the Faith
